

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-appdb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${DB_NAME:-appdb}"]
      interval: 5s
      timeout: 5s
      retries: 5
  migrations:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_NAME: ${DB_NAME:-appdb}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT:-5432}
      DB_DRIVER: ${DB_DRIVER:-postgresql+psycopg2}
    command: sh -c "alembic upgrade head"
  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    environment:
      DB_NAME: ${DB_NAME:-appdb}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT:-5432}
      DB_DRIVER: ${DB_DRIVER:-postgresql+psycopg2}
    ports:
      - 8000:8000
    command: > 
      sh -c "python ./main.py"
volumes:
  postgres_data: